<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="A_4_PRG_MasterSystemTime" Id="{7173042a-7f7f-45b8-b04e-de7c8939b16f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM A_4_PRG_MasterSystemTime
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

]]></ST>
    </Implementation>
    <LineIds Name="A_4_PRG_MasterSystemTime">
      <LineId Id="394" Count="0" />
      <LineId Id="223" Count="0" />
      <LineId Id="220" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>